<!-- Flash Sale Modal -->
<div class="modal fade" id="flashSaleModal" tabindex="-1" aria-labelledby="flashSaleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content border-0 shadow-lg" style="background: #fff;">
            <div class="modal-header border-0 p-0" style="background: linear-gradient(135deg, #FF6B6B 0%, #FF8E72 100%); color: white;">
                <h5 class="modal-title fw-bold p-4 mb-0" id="flashSaleModalLabel">
                    <i class="bi bi-lightning-fill me-2"></i>⚡ FLASH SALE - HỘT HẠNG NGAY!
                </h5>
                <button type="button" class="btn-close btn-close-white me-3 mt-3" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <div class="modal-body p-0 position-relative" id="flashSaleCarousel">
                <!-- Carousel will be loaded here by JavaScript -->
                <div class="text-center py-5">
                    <div class="spinner-border text-primary" role="status">
                        <span class="visually-hidden">Đang tải...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Flash Sale Carousel Template (hidden, used by JS) -->
<template id="flashSaleCarouselTemplate">
    <div class="carousel slide position-relative" id="flashSaleCarouselInner" data-bs-interval="false">
        <!-- Indicators -->
        <div class="carousel-indicators position-absolute bottom-0 start-50 translate-middle-x mb-3" id="flashSaleIndicators">
            <!-- Generated by JS -->
        </div>
        
        <!-- Items -->
        <div class="carousel-inner" id="flashSaleCarouselItems">
            <!-- Generated by JS -->
        </div>
        
        <!-- Previous Button -->
        <button class="carousel-control-prev position-absolute start-0 top-50 translate-middle-y" type="button" data-bs-target="#flashSaleCarouselInner" data-bs-slide="prev" style="width: 50px; height: 50px; background: rgba(255,107,107,0.8); border: none; border-radius: 50%; z-index: 10; left: 10px;">
            <i class="bi bi-chevron-left text-white" style="font-size: 1.5rem;"></i>
        </button>
        
        <!-- Next Button -->
        <button class="carousel-control-next position-absolute end-0 top-50 translate-middle-y" type="button" data-bs-target="#flashSaleCarouselInner" data-bs-slide="next" style="width: 50px; height: 50px; background: rgba(255,107,107,0.8); border: none; border-radius: 50%; z-index: 10; right: 10px;">
            <i class="bi bi-chevron-right text-white" style="font-size: 1.5rem;"></i>
        </button>
    </div>
</template>

<!-- Flash Sale Item Template (hidden, used by JS) -->
<template id="flashSaleItemTemplate">
    <div class="carousel-item active">
        <div class="p-4" style="min-height: 500px;">
            <div class="row g-4 align-items-center h-100">
                <!-- Image -->
                <div class="col-md-5">
                    <div class="position-relative overflow-hidden rounded-3" style="height: 380px; background: #f8f9fa;">
                        <img src="" class="flash-sale-image w-100 h-100" style="object-fit: cover;" alt="Flash Sale">
                        <div class="position-absolute top-3 end-3 badge bg-danger fs-5 flash-sale-discount" style="padding: 10px 15px; font-size: 1.1rem;">
                            <i class="bi bi-lightning-fill"></i> <span class="discount-percent">-0%</span>
                        </div>
                    </div>
                </div>
                
                <!-- Details -->
                <div class="col-md-7">
                    <h5 class="fw-bold mb-3 flash-sale-title" style="font-size: 1.5rem;"></h5>
                    <p class="text-muted mb-4 flash-sale-description" style="font-size: 1rem;"></p>
                    
                    <!-- Price -->
                    <div class="mb-4 pb-3 border-bottom">
                        <div class="row align-items-baseline">
                            <div class="col-auto">
                                <span class="fs-2 fw-bold text-danger flash-sale-price" style="font-size: 2rem;"></span>
                            </div>
                            <div class="col-auto">
                                <span class="text-muted text-decoration-line-through flash-sale-original-price" style="font-size: 1.1rem;"></span>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Countdown Timer -->
                    <div class="mb-4 p-4 rounded-3" style="background: linear-gradient(135deg, #FFF3E0 0%, #FFE0B2 100%); border-left: 5px solid #FF6B6B;">
                        <small class="text-muted d-block mb-3 fw-bold" style="font-size: 0.95rem;">⏱️ KẾT THÚC TRONG:</small>
                        <div class="flash-sale-countdown d-flex justify-content-around align-items-center">
                            <div class="text-center">
                                <div class="fs-3 fw-bold text-danger countdown-hours" style="font-family: 'Courier New', monospace; font-size: 2rem;">00</div>
                                <small class="text-muted fw-bold" style="font-size: 0.85rem;">GIỜ</small>
                            </div>
                            <span class="fw-bold text-muted fs-5">:</span>
                            <div class="text-center">
                                <div class="fs-3 fw-bold text-danger countdown-minutes" style="font-family: 'Courier New', monospace; font-size: 2rem;">00</div>
                                <small class="text-muted fw-bold" style="font-size: 0.85rem;">PHÚT</small>
                            </div>
                            <span class="fw-bold text-muted fs-5">:</span>
                            <div class="text-center">
                                <div class="fs-3 fw-bold text-danger countdown-seconds" style="font-family: 'Courier New', monospace; font-size: 2rem;">00</div>
                                <small class="text-muted fw-bold" style="font-size: 0.85rem;">GIÂY</small>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Stock Progress Bar -->
                    <div class="mb-4">
                        <div class="d-flex justify-content-between mb-2">
                            <small class="text-muted fw-bold">📦 SỐ LƯỢNG CÒN LẠI:</small>
                            <small class="fw-bold text-danger flash-sale-remaining-stock">0</small>
                        </div>
                        <div class="progress" style="height: 12px; background: #e9ecef;">
                            <div class="progress-bar flash-sale-progress-bar" role="progressbar" style="width: 0%; background: linear-gradient(90deg, #FF6B6B 0%, #FF8E72 100%);"></div>
                        </div>
                        <small class="text-muted d-block mt-2 text-center flash-sale-stock-sold">Đã bán: 0%</small>
                    </div>
                    
                    <!-- Add to Cart Button -->
                    <button class="btn btn-danger btn-lg w-100 fw-bold flash-sale-add-btn" style="background: linear-gradient(135deg, #FF6B6B 0%, #FF8E72 100%); border: none; padding: 14px 24px; font-size: 1.1rem; cursor: pointer;">
                        <i class="bi bi-cart-plus me-2"></i>THÊM VÀO GIỎ HÀNG
                    </button>
                    <small class="text-muted d-block mt-3 text-center">✅ Miễn phí vận chuyển cho đơn từ 500.000đ</small>
                </div>
            </div>
        </div>
    </div>
</template>

<!-- Flash Sale Notification Badge (for sticky header or floating) -->
<div id="flashSaleNotification" class="flash-sale-notification d-none position-fixed" style="top: 80px; right: 20px; z-index: 999;">
    <div class="badge bg-danger p-4 rounded-4 shadow-lg d-flex align-items-center gap-3" style="cursor: pointer; border: 3px solid #fff; box-shadow: 0 8px 24px rgba(255, 107, 107, 0.4), 0 0 0 3px #fff;" data-bs-toggle="modal" data-bs-target="#flashSaleModal">
        <i class="bi bi-lightning-fill animate-pulse" style="font-size: 1.5rem;"></i>
        <span class="fw-bold" style="font-size: 1.1rem;">FLASH SALE!</span>
        <span class="badge bg-light text-danger ms-2 fw-bold flash-sale-notify-countdown" style="font-size: 0.95rem;">00:00</span>
    </div>
</div>
